# Generated by Django 5.1.4 on 2025-01-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendence_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
