# Generated by Django 5.1.4 on 2025-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_course_course_name_alter_staff_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('GIRL', 'Girl'), ('BOY', 'Boy'), ('OTHERS', 'Others')], max_length=255),
        ),
    ]
