# Generated by Django 5.1.4 on 2025-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_leavereportstaff_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='attendence_date',
            field=models.DateField(),
        ),
    ]
