# Generated by Django 5.1.4 on 2025-02-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_staff_fcm_token_student_fcm_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fcm_token',
        ),
    ]
